### ISSUE TITLE
Build on macOS catalina 64bit

### ISSUE THREAD

**Issue by bttd** [ioquake/launch#15]
Hi!

Earlier I use this script, to install ioquake3 on may mac.: 

https://github.com/diegoulloao/ioquake3-mac-install

This script downloads a prebuild version of ioquake3 with launcher. The only problem is, after new Catalina upgrade on macOS there is no way to run 32bit application. 

I can build ioquake3 for myself with the included script, to make it work again, but I'm unable to build this launcher since the wiki with instructions won't work.

Anyone can give me instructions about mac build?

**Comment by NuclearMonster** [comment]
Please use our forum to discuss building the game or launcher, https://discourse.ioquake.org/ and the wiki can still be accessed via archive.org

**Comment by NuclearMonster** [comment]
Please also note that the above script is highly insecure and downloads a version of ioquake3 from a random Dropbox account.

**Comment by bttd** [comment]
Thanks!

Yes I know, not this is the most secure, but the script actually downloads the game what I build myself.

**Comment by diegoulloao** [comment]
> Please also note that the above script is highly insecure and downloads a version of ioquake3 from a random Dropbox account.

Now all downloads are directly from repository and official ioquake3 servers
Check dev branch.

**Comment by diegoulloao** [comment]
> ... and the wiki can still be accessed via archive.org

Actually not for this. Because was a php dynamic page (select for mac): https://web.archive.org/web/20160914022911/http://wiki.ioquake3.org/Building_launch

**Comment by diegoulloao** [comment]
> Thanks!
> 
> Yes I know, not this is the most secure, but the script actually downloads the game what I build myself.

That was builded for @bttd from source code not test build ;)

**Comment by diegoulloao** [comment]
> Please use our forum to discuss building the game or launcher

I opened a discussion here: https://discourse.ioquake.org/t/ioquake3-lauch-how-to-build-64-bits-for-macos-catalina/1373

I'll appreciate any kind of help.
